import { useSyncExternalStore } from "react";

// Real Minecraft item/block icons, generated by scripts/gen_item_icons.mjs into
// public/itemIcons.json (a { name: dataURL } map). Fetched once at module load
// and cached; components read it through useItemIcons(). Kept out of the JS
// bundle (it's ~540 KB) so it loads as a separate cacheable asset.
//
// The <ItemIcon> renderer lives in components/ItemIcon.tsx (split so this file
// only exports a hook — keeps react-refresh happy).

type IconMap = Record<string, string>;

let icons: IconMap | null = null;
const listeners = new Set<() => void>();

function notify() {
  for (const l of listeners) l();
}

// Fire the fetch immediately on first import.
fetch("/itemIcons.json")
  .then((r) => (r.ok ? r.json() : {}))
  .then((data: IconMap) => {
    icons = data;
    notify();
  })
  .catch(() => {
    icons = {}; // give up gracefully — components fall back to text
    notify();
  });

function subscribe(cb: () => void) {
  listeners.add(cb);
  return () => listeners.delete(cb);
}

/** Returns a lookup `(name) => dataURL | undefined`. Re-renders when the icon
 *  map finishes loading. */
export function useItemIcons(): (name: string) => string | undefined {
  useSyncExternalStore(
    subscribe,
    () => icons,
    () => icons,
  );
  return (name: string) => icons?.[name];
}
