#!/usr/bin/env python3
"""Generate the code-derived reference docs for the mineclaude skill.

Emits the three reference files under skills/mineclaude/ by introspecting the
live code, so the API reference can't drift from the implementation:

    primitives.md  — every primitive in make_primitives (signature + docstring)
    events.md      — reflex event types + their default reaction policy
    tools.md       — the MCP tool schemas (from the FastMCP server)

The hand-written skill docs (SKILL.md, mental-model.md, snippets.md,
handlers.md) are NOT touched. Re-run after changing primitives, reflex
handlers, or MCP tools:

    .venv/bin/python scripts/gen_skill_docs.py
"""

from __future__ import annotations

import asyncio
import inspect
import sys
from pathlib import Path

# Allow running as `python scripts/gen_skill_docs.py` from the repo root.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from agent.bridge import MockBridgeClient
from agent.primitives import make_primitives
from agent.reflexes import REFLEX_EVENT_TYPES, ReflexRegistry, register_default_handlers
from agent.runtime import Runtime, _DEFAULT_EVENT_POLICY

SKILL_DIR = Path(__file__).resolve().parent.parent / "skills" / "mineclaude"
GENERATED = "<!-- GENERATED by scripts/gen_skill_docs.py — do not edit by hand. -->"


def gen_primitives() -> str:
    # No on_subaction → unwrapped closures, so signatures/docstrings are clean.
    prims = make_primitives(MockBridgeClient())
    out = [
        GENERATED,
        "",
        "# Primitives",
        "",
        "The async functions preloaded into `execute(code=...)`. `await` every call "
        "except `log`. `say(...)` is how the bot talks (chat is not a tool). `math` is "
        "preloaded; `import` and dunder access are blocked.",
        "",
    ]
    for name, fn in prims.items():
        sig = str(inspect.signature(fn))
        prefix = "" if name == "log" else "await "
        out.append(f"### `{prefix}{name}{sig}`")
        doc = inspect.getdoc(fn)
        if doc:
            out += ["", doc]
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def gen_events() -> str:
    reg = ReflexRegistry(_NullController())
    register_default_handlers(reg)
    out = [
        GENERATED,
        "",
        "# Events & reaction policy",
        "",
        "Two event surfaces (see `get_state`):",
        "",
        "- **`reflexes_recent`** — a rolling buffer of *hazard* reflex fires. These "
        "react instantly via the registry; you observe them after the fact.",
        "- **`events`** — a flushable buffer of everything else (chat / death / respawn "
        "+ the mod's world-mutation log). `get_state(flush=True)` drains it; "
        "`wait_for_event` blocks on it.",
        "",
        "Install your own reaction body for any event type with `set_handler` "
        "(see handlers.md). The defaults below are what runs until you do.",
        "",
        "## Hazard events (react via the reflex registry)",
        "",
        "| event | preempts | cooldown_s | resumes | default reaction |",
        "|---|---|---|---|---|",
    ]
    notes = {
        "damage_taken": "hostile mob → retaliate (HP>6) or flee (HP≤6); fall/fire/player/phantom → record-only",
        "entered_lava": "walk to nearest shore",
        "started_drowning": "surface, then walk to shore",
        "tool_broke": "record-only (you decide whether to re-equip)",
        "hostile_nearby": "awareness only — never preempts, never wakes you",
    }
    for et in REFLEX_EVENT_TYPES:
        h = reg.get(et)
        if h is None:
            continue
        out.append(
            f"| `{et}` | {h.preempts} | {h.cooldown_s:g} | {h.resumes_on_complete} | "
            f"{notes.get(et, '')} |"
        )
    out += [
        "",
        "## Other events (recorded to the flushable buffer)",
        "",
        "| event | default preempts | behaviour |",
        "|---|---|---|",
    ]
    other_notes = {
        "chat": "a player said something — recorded only",
        "death": "the bot died — preempts the action slot, then recorded",
        "respawn": "recorded only",
    }
    for et, preempts in _DEFAULT_EVENT_POLICY.items():
        out.append(f"| `{et}` | {preempts} | {other_notes.get(et, '')} |")
    out += [
        "",
        "Plus `reflex_done` (synthesized when a hazard handler finishes recovering) and "
        "the mod's world-mutation events (`block_broken`, `block_placed`, "
        "`entity_attacked`) which arrive via `get_state(flush=True)` with `{type, data, ts}`.",
        "",
    ]
    return "\n".join(out).rstrip() + "\n"


def gen_tools() -> str:
    from agent.mcp_server import build_mcp

    async def _list():
        mcp = build_mcp(Runtime(MockBridgeClient()))
        return await mcp.list_tools()

    tools = asyncio.run(_list())
    out = [
        GENERATED,
        "",
        "# MCP tools",
        "",
        "The tools the server exposes. `say(message)` is **not** a tool — it is a "
        "primitive you call inside `execute`.",
        "",
    ]
    for t in sorted(tools, key=lambda x: x.name):
        out.append(f"## `{t.name}`")
        out.append("")
        if t.description:
            out += [t.description, ""]
        props = (t.inputSchema or {}).get("properties") or {}
        required = set((t.inputSchema or {}).get("required") or [])
        if props:
            out.append("| arg | type | required | default |")
            out.append("|---|---|---|---|")
            for arg, spec in props.items():
                typ = spec.get("type") or spec.get("anyOf") or "—"
                default = spec.get("default", "")
                out.append(f"| `{arg}` | {typ} | {arg in required} | {default} |")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


class _NullController:
    """Minimal Controller stand-in for introspecting registry policy offline."""

    bridge = None

    async def preempt(self) -> None: ...
    def resume(self, event_type: str) -> None: ...
    def slog(self, event: str, **data) -> None: ...
    async def emit_event(self, event: str, data=None) -> None: ...


def main() -> None:
    SKILL_DIR.mkdir(parents=True, exist_ok=True)
    for fname, gen in (
        ("primitives.md", gen_primitives),
        ("events.md", gen_events),
        ("tools.md", gen_tools),
    ):
        (SKILL_DIR / fname).write_text(gen())
        print(f"wrote {SKILL_DIR / fname}")


if __name__ == "__main__":
    main()
